export const SET_LOADING_ON = 'SET_LOADING_ON';
export const SET_LOADING_OFF = 'SET_LOADING_OFF';
export const SET_SHOW_MENU_ON = 'SET_SHOW_MENU_ON';
export const SET_SHOW_MENU_OFF = 'SET_SHOW_MENU_OFF';